### ISSUE TITLE
Errors on Safari

### ISSUE THREAD

**Issue by p16i** [brain-web/brain-web.github.io#12]
Hi,

The sign in button seems not working. I get the error below

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/1214890/78051382-e2b76f00-737d-11ea-95f3-0003266b0dcc.png">

My safari version is: Version 13.0.2 (15608.2.30.1.1).

There are also some errors on the front page
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/1214890/78051480-0b3f6900-737e-11ea-80a9-d3eab1e9a85e.png">

**Comment by katjaq** [comment]
Ah wow! 😲 we didn't test on Safari . Sorry. But I can reproduce the same error here. We'll look into it. 
Thank you for reaching out to us.

**Comment by katjaq** [comment]
hey @heytitle – check now :) it should work :)
Also, the landing page should now display nicely :)
Thanks again! and sorry for the trouble.

**Comment by p16i** [comment]
hi @katjaq , thanks for the fix.

It looks good now!

**Comment by p16i** [comment]
Actually, I also observer that the main animation on the lading page has a strange white border. I see it on both Safari and Chrome, and I could not find what is the actual cause.

<img width="577" alt="image" src="https://user-images.githubusercontent.com/1214890/78121624-e691d280-740b-11ea-9cb0-8158282b70dd.png">

**Comment by katjaq** [comment]
Hello! Happy it works now :)
Yes, this border is actually not a bug. Thought it makes sense to keep it as it is the border of the landing page, which separates the voronoi charts on the landing page from the content part of the website upon scroll down. Do you think it's ugly? Or is the size not calculated correctly in Safari? (That has been nicely working for me yesterday, but maybe it doesn't work everywhere? )
When you freshly open the page, the white border should be "invisible" at the very bottom aligned with your screen. It is not only the white border, also the voronoi diagrams have a black background which set them apart from the slightly lighter background of the rest of the page. You think it's okay?

**Comment by p16i** [comment]
I notice the different black shade between the diagram and the rest of the page. For me, it's ok and actually it was because of that made me think the border is not necessary. 

I think it's ok to leave it like that.
