### ISSUE TITLE
Error when accessing "community" as a new user

### ISSUE THREAD

**Issue by kchapelier** [brain-web/brain-web.github.io#22]
Hi,

I encountered an error when I tried to access the page after signing in.

 * Browsing with Chrome
 * Went to the community page, the graph is properly displayed 
 * Signed in as a new user with Github
 * Community page refreshed itself
 * Appear properly signed in, github avatar and username are shown in the header
 * The graph is not displayed anymore and there is an error in the console
 * If I sign out, the graph is properly displayed once again

![brainweb-console-error](https://user-images.githubusercontent.com/5741699/79026606-acea6580-7b89-11ea-8dcd-b2480e2e364b.png)

![brainweb-source-error](https://user-images.githubusercontent.com/5741699/79026612-b247b000-7b89-11ea-8813-300ef30cf63c.png)

app.uid is properly set to some number, but my account does not appear in app.people.

**Comment by r03ert0** [comment]
hello @kchapelier! Thank you so much for taking the time to have a look at our code, it's really awesome 🚀! I follow you on twitter and really love the procedural art you've done 😄 
If you are up for some neurosci web apps, we'd really appreciate having your advice!

**Comment by kchapelier** [comment]
You're welcome. I'm adding myself to the network as I'm always interested to do some performance optimization work (among other things) in JavaScript, as I did on [mls-mpm.js](https://github.com/r03ert0/mls-mpm.js) about a year ago. 😉
