### ISSUE TITLE
Idea: Skill proficiency

### ISSUE THREAD

**Issue by anibalsolon** [brain-web/brain-web.github.io#5]
Hi @katjaq and @r03ert0

The website is amazing, congrats! The Voronoi is indeed hypnotizing 😄and the idea is magnificent, the link via Github topic is 🤯

If I understood correctly, people will include their skills and it will match them with projects that might need help, is that correct? If so, it would be nice if a person could also include proficiency (although subjective) from e.g 1 to 5 and maybe something like "interested to learn", so it could link e.g. a proficient pythonist and a wannabe to the same project, to stimulate this knowledge sharing. @complexbrains brought up the great point about possible biases that it might incur (towards people w more proficiency), but we are not sure how it could affect the process.

Of course, the matching algorithm is an on-going thing, and I guess we will learn more about it later :)

Eager to collaborate with the project! 🤗

**Comment by r03ert0** [comment]
it'd be nice to pimp that skills dialog! The main issue to take into account will be user experience (you don't want to make the process too slow, or make a complex interface). Maybe we could use the next hackathon to try out possible interfaces? We've been using Quasar for the development, and it comes with a lot of nice widgets which could be tried out. Check https://quasar.dev/start

In addition, we could import skills from LinkedIn? Let people enter their twitter handle? Link to their GitHub repos?

**Comment by katjaq** [comment]
@anibalsolon thanks for joining in! and for the kind words :D 
For the moment we are not matching people with projects, we are building the network based on shared skills, weighted. We'd like to add project filtering and more soon :) For the moment, issues in the repos indexed in BrainWeb could be tagged so people find their best match...

**Comment by anibalsolon** [comment]
Yes @r03ert0 I definitely understand the UX issue- we could extend the QSelect and QChip components to provide this input for the user, e.g. 
![image](https://user-images.githubusercontent.com/562525/77834972-fad98500-7116-11ea-916a-a11236fceeb9.png)
and it would also need to extend the data model of the selector, so as to allow this info to be stored. But I digress 🙃 
Since we already have their token from Github, it should be potentially trivial to gather which projects within the topic #brainweb they collaborate, to at least suggest skills to input.

@katjaq yay! 🎉 🤗 
yes, one step at the time 😅and being issue-oriented is a great idea, way more direct on how one could collaborate with the project!

I will close here for further discussion on the channel 🤗 Thank you both for the feedback!
