### ISSUE TITLE
Community: add a guideline wrt to the color coding

### ISSUE THREAD

**Issue by sofievdbos** [brain-web/brain-web.github.io#7]
Great work! ❤️  
I don't know whether I missed it (it's already late here) or if it's not there yet, but how can you change the color code of your dot based on selecting one of your keywords? So, e.g. I want to see the network of all Open Science people --> can I get those dots which selected Open Science as a keyword in a specific color by somehow selecting the keyword? Or how should I interpret the color coding atm? 

Please ask me if I don't make any sense! 🤗

**Comment by sofievdbos** [comment]
Something else related to the Community tab: as the community (network) will grow, it could be nice if our own name would be highlighted in the network upon signing in. So that we don't have to search for it. 😄

**Comment by r03ert0** [comment]
Hi Sofie,
Thank you for your feedback 😄 
The colours come from groups obtained by clustering the network (hierarchical clustering for the moment). We build a 'skills matrix' which we cluster, and then we cut the dendrogram to have a certain number of groups (we use sqrt(N), where N is the number of participants). The colours are just a default "10 classes" in d3, which is the library we use for plotting the network (we'll have to revisit our choice when we'll have >100 users 😛).
So, we can't really predict what the clusters are about... they very much depend on what people are entering as skills. It should be possible, though, to try to figure out which are the skills that characterise each cluster (the Open Science cluster seems to be one).
We're using brainhack's mattermost to discuss BrainWeb UI/UX and perspectives (like a newsletter and stuff). Would you like to join? Once in the mattermost, it's the ~brainweb channel. We can also work on it for the hackathon!
