### ISSUE TITLE
Find a way to easily add skills to one's profile

### ISSUE THREAD

**Issue by Remi-Gau** [brain-web/brain-web.github.io#8]
As more people sign in the cloud of users might get too complicated for one to find one's position to click on their dot and add skills. 

Maybe we should add a drop down menu in the sign-in section

**Comment by sofievdbos** [comment]
Linked to my follow-up remark in issue #7?

**Comment by sofievdbos** [comment]
Another cool item could be to see which skill keywords were added between your last login and your current login (to add more if applicable). Just brainstorming with I, me and myself.

**Comment by katjaq** [comment]
Thank you for sharing your concerns and ideas here! That's great! We will try to improve things / add options as fast as possible. @r03ert0 suggested linking skills editing to the user name in the sign in panel at some point, when there will be too many dots. (That would be so lovely if the community keeps growing <3)

**Comment by Remi-Gau** [comment]
> Thank you for sharing your concerns and ideas here! That's great! We will try to improve things / add options as fast as possible.

No worries @katjaq. I tend to see github issues as a to-do list or a wish list. So I often put things there just so I or we don't forget. The rank of priority can be decided later.
But it also means that they can be a bit short and abrupt. Sorry. :-/

**Comment by Remi-Gau** [comment]
closing old issues of mine
