### ISSUE TITLE
skills duplicate

### ISSUE THREAD

**Issue by Remi-Gau** [brain-web/brain-web.github.io#9]
We might want to check, sort and suggest skills because we already have duplicate because of case issues, hyphenation and similar spelling extravaganza.

**Comment by r03ert0** [comment]
these are all the skills we have at the moment. Any idea for a nice regex spell?

" 7T MRI", " C++", " Complex Networks", " EEG", " Epilepsy", " image segmentation", " layer fMRI", " Learning", " Machine Learning", " Mathematical Modelling", " MEG", " multisensory", " Network Neuroscience", " Pytorch", " R-project", " visual cortex", "3DSlicer", "AffectiveNeuroscience", "Agent-based Modeling", "Animal experiment", "Animal Imaging", "Artificial Life", "auditory cortex", "Bash", "Behavior", "Cerebrovascular Reactivity", "CognitiveNeuroscience", "Continual learning", "cortical modelling", "DataViz", "Deep Learning", "Dementia", "Development", "Diffusion MRI", "Dynamic Functional Connectivity", "ECoG", "EEG Source Localisation", "Electrophysiology", "Evolution", "fMRI", "Functional Connectivity", "Genomics", "Graph Theory", "Guidelines", "haemodynamics", "High-Field (f)MRI", "High-performance computing", "HRF", "Image registration", "In-vitro", "JavaScript", "Laminar fMRI", "Language", "Lateralization", "Matlab", "Memory", "mesh processing", "Multi-Echo BOLD fMRI", "Multimodal Imaging", "MVPA", "Neuroanatomy", "Neuroimaging", "Neuropsychology", "Neuropsycology", "Non-human primate", "octave", "Open Science", "Physiology", "Population analysis", "Python", "Quality Control", "R", "resting-state", "SciArt", "SPM", "Statistics", "Structural Connectivity", "subcortical imaging", "substance use disorders", "Time Series Analysis", "ultra high field MRI", "Virtual Reality", "Web Development"

**Comment by Remi-Gau** [comment]
closing old issues of mine
